segundo pull request creando rama
ErickGonzalez3d/Hyperblog pull request #7
Opened 2021-08-19 15:20 UTC by ErickGonzalez3d

este pull es del autor y owner

2021-08-19 15:22 UTC, erickjgc1 commented
este es el comentario del colaborador

2021-08-19 15:24 UTC, erickjgc1 requested changes
El colaborador ha rechazado los cambios

2021-08-20 00:00 UTC, ErickGonzalez3d reviewed
este cambio es del propio autor no necesita un approve y tampoco puede hacerse un request changes el mismo

2021-08-20 00:03 UTC, ErickGonzalez3d commented
el autor corrige la petición

2021-08-20 00:50 UTC, merged